apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: terraformers-target

resources:
  - ../../base
  - namespace.yaml
  - opensearch-service.yaml
  - opensearch-statefulset.yaml

patches:
  - path: backend-configmap-patch.yaml

images:
  - name: public.ecr.aws/example/terraformers-backend
    newName: registry.example.com/terraformers-backend
    newTag: immutable-target-sha
