apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: terraformers-target

resources:
  - ../../base
  - namespace.yaml
  - opensearch-storageclass.yaml
  - opensearch-service.yaml
  - opensearch-statefulset.yaml

patches:
  - path: backend-configmap-patch.yaml

images:
  - name: public.ecr.aws/example/terraformers-backend
    newName: asia-northeast3-docker.pkg.dev/terraformers-platform/terraformers-backend/terraformers-backend
    digest: sha256:a9331bc8026075390cedd8bfcdc8625b5cc69cdf16cd3799e2029beff6f857ae
