apiVersion: v1
kind: Service
metadata:
  name: terraformers-opensearch
  labels:
    app.kubernetes.io/name: terraformers-opensearch
    app.kubernetes.io/part-of: terraformers-modernization
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: terraformers-opensearch
  ports:
    - name: http
      port: 9200
      targetPort: http
