apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: terraformers-backend-runtime-secrets
  namespace: terraformers-target
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/terraformers-platform/secrets/terraformers-mariadb-app-password/versions/latest"
        path: "mariadb-app-password"
