apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: terraformers-backend-runtime-secrets
  namespace: terraformers-target
spec:
  serviceAccountName: terraformers-secret-sync
  secretProviderClassName: terraformers-backend-runtime-secrets
  secretObject:
    type: Opaque
    data:
      - sourcePath: "mariadb-app-password"
        targetKey: "SPRING_DATASOURCE_PASSWORD"
