#!/usr/bin/env python3
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
LEDGER=ROOT/".agents/state/case-c-architecture-closure.json"
PLAN=ROOT/"docs/plans/active/case-c-architecture-closure.md"
AI=ROOT/"docs/AI_PROJECT_STATE.md"
PORTFOLIO=ROOT/"docs/plans/active/portfolio-case-reassessment.md"
CAPACITY=ROOT/".agents/work-packages/case-c-capacity-baseline-v1.yml"
START="<!-- CASE_C_ARCHITECTURE_CLOSURE:START -->"
END="<!-- CASE_C_ARCHITECTURE_CLOSURE:END -->"
ISSUE_STATUSES={"OPEN","IN_PROGRESS","EVIDENCE_PENDING","RESOLVED","DEFERRED","ACCEPTED_RESIDUAL"}
SEVERITIES={"BLOCKER","HIGH","RESIDUAL"}
PHASE_STATUSES={"COMPLETE","AWAITING_DECISION_APPROVAL","BLOCKED","ACTIVE","DEFERRED"}

def load():
    data=json.loads(LEDGER.read_text(encoding="utf-8"))
    phases=data.get("phases",[]); issues=data.get("issues",[])
    if data.get("schema_version")!=1 or data.get("case")!="case-c": raise SystemExit("invalid ledger identity")
    if [p.get("id") for p in phases] != [f"C{i}" for i in range(9)]: raise SystemExit("phase IDs/order changed")
    if [i.get("id") for i in issues] != [f"C-ARCH-{i:02d}" for i in range(1,13)]: raise SystemExit("issue IDs/order changed")
    phase_ids={p["id"] for p in phases}
    for p in phases:
        if p.get("status") not in PHASE_STATUSES or not set(p.get("requires",[]))<=phase_ids or not isinstance(p.get("live_action"),bool): raise SystemExit("invalid phase contract")
    for i in issues:
        if i.get("severity") not in SEVERITIES or i.get("status") not in ISSUE_STATUSES: raise SystemExit("invalid issue classification")
        if i.get("owner_phase") not in phase_ids or not set(i.get("blocks",[]))<=phase_ids: raise SystemExit("invalid issue dependency")
        if not i.get("evidence") or not i.get("acceptance"): raise SystemExit("issue evidence/acceptance missing")
    if set(data.get("automation",{}).get("lanes",{})) != {"M0_MECHANICAL_SYNC","M1_EVIDENCE_STATE","D_DECISION"}: raise SystemExit("maintenance lane set changed")
    unresolved=[i["id"] for i in issues if i["severity"]=="BLOCKER" and i["status"]!="RESOLVED"]
    if unresolved and data.get("capacity_baseline_status")!="SUSPENDED_BY_ARCHITECTURE_AUDIT": raise SystemExit("capacity baseline resumed with unresolved blockers")
    return data

def blockers(d): return [i["id"] for i in d["issues"] if i["severity"]=="BLOCKER" and i["status"]!="RESOLVED"]

def plan(d):
    cur=next(p for p in d["phases"] if p["id"]==d["current_phase"])
    o=["# Case C Architecture Closure","",
       "> Generated from .agents/state/case-c-architecture-closure.json.",
       "> Do not edit this file directly. Run: python3 scripts/checks/case_c_architecture_ledger.py --sync","",
       "## Control state","",
       f"- Overall status: **{d['overall_status']}**",
       f"- Capacity baseline: **{d['capacity_baseline_status']}**",
       f"- Audit base SHA: {d['audit_base_sha']}",
       f"- Current phase: **{d['current_phase']} — {cur['title']}**",
       f"- Open blocking issues: {', '.join(blockers(d)) or 'none'}","",
       "Capacity baseline and later hardening phases are deferred by the approved portfolio-sufficiency decision; they are not prerequisites for Case C portfolio closure.","",
       "## Phase dependency graph","",
       "| Phase | Status | Purpose | Requires | Live action |","|---|---|---|---|---|"]
    for p in d["phases"]: o.append(f"| {p['id']} | {p['status']} | {p['title']} | {', '.join(p['requires']) or '—'} | {'yes' if p['live_action'] else 'no'} |")
    o += ["","## Issue register","","| ID | Severity | Status | Owner | Blocks | Finding |","|---|---|---|---|---|---|"]
    for i in d["issues"]: o.append(f"| {i['id']} | {i['severity']} | {i['status']} | {i['owner_phase']} | {', '.join(i['blocks']) or '—'} | {i['title']} |")
    o += ["","## Acceptance and retained evidence",""]
    for i in d["issues"]:
        o += [f"### {i['id']} — {i['title']}","",f"- Severity/status: {i['severity']} / {i['status']}",f"- Owner phase: {i['owner_phase']}","- Retained evidence:"]
        o += [f"  - {x}" for x in i["evidence"]]; o += ["- Acceptance:"]; o += [f"  - {x}" for x in i["acceptance"]]; o += [""]
    o += ["## Maintenance automation lanes","","| Lane | Per-PR user decision | Agent merge | Boundary |","|---|---|---|---|"]
    for name,l in d["automation"]["lanes"].items():
        merge="allowed after checks + independent evidence review" if l.get("agent_merge_allowed_after_checks_and_independent_evidence_review") else ("allowed after checks" if l.get("agent_merge_allowed_after_checks") else "not allowed")
        o.append(f"| {name} | {'required' if l['user_per_pr_decision_required'] else 'not required'} | {merge} | {l['rule']} |")
    o += ["","The maintenance lane never authorizes production/runtime source changes, workflow behavior changes, IaC changes, dependency changes, live/cloud/IAM/cost actions, acceptance changes, architecture choices, or new failure-class scope.","","## Operating rules","",
          "1. Map every new Case C failure to an existing C-ARCH item before creating a new issue ID.",
          "2. Never delete resolved findings; preserve their status and evidence.",
          "3. Deferred production-hardening phases are not an automatic execution queue; reopen only from a new operational requirement or explicit user decision.",
          "4. CI PASS does not resolve an issue unless that issue's predeclared acceptance is directly satisfied.",
          "5. Capacity execution is deferred after portfolio closure and must not be restarted solely to obtain a green historical result.",
          "6. Architecture, acceptance, severity, ownership, residual-risk, and scope decisions use D_DECISION and require user approval.",""]
    return "\n".join(o)

def state(d):
    cur=next(p for p in d["phases"] if p["id"]==d["current_phase"])
    return "\n".join([START,"### Case C portfolio closure control","",f"- Overall: **{d['overall_status']}**",f"- Capacity baseline: **{d['capacity_baseline_status']}**",f"- Current phase: **{d['current_phase']} — {cur['title']} ({cur['status']})**",f"- Open blockers: {', '.join(blockers(d)) or 'none'}","- Durable issue register: .agents/state/case-c-architecture-closure.json","- Generated plan: [Case C Architecture Closure](plans/active/case-c-architecture-closure.md)","- Portfolio closure: [Case C Final Portfolio Closure](evaluation/case-c-portfolio-closure.md)","- Failed capacity run 36957682821 and C2 run 37016993776 are retained as evidence, not rerun obligations.","- Capacity and deferred hardening phases reopen only for a new operational requirement or explicit user-approved portfolio revision.",END])

def portfolio(d):
    cur=next(p for p in d["phases"] if p["id"]==d["current_phase"])
    return "\n".join([START,"## Case C portfolio-closure checkpoint","",f"Case C is **{d['overall_status']}**. The capacity baseline is **{d['capacity_baseline_status']}**; run 36957682821 is retained as evidence that functional correctness failed before any valid saturation result.","",f"The closure phase is **{d['current_phase']} — {cur['title']}** ({cur['status']}). Open blockers are {', '.join(blockers(d)) or 'none'}.","","The selected portfolio case is **Cloud Runtime Measurement Guardrails & Immutable Delivery**. Final evidence is [Case C Final Portfolio Closure](../../evaluation/case-c-portfolio-closure.md). C2 run 37016993776 is retained as a 1/5 fail-closed result showing real Terraform executable-validity variance. Capacity tuning, desired-state convergence, rollout-under-load, and faulty-release rollback are deferred production-hardening work rather than portfolio prerequisites.",END])

def task(d):
    cur=next(p for p in d["phases"] if p["id"]==d["current_phase"])
    return f"- Current single task: **Portfolio representative-case work is closed with explicit residuals. Case C is {d['overall_status']}; deferred capacity/hardening work requires a new explicit operational or portfolio decision.**"

def replace_block(text,b):
    if START in text or END in text:
        if text.count(START)!=1 or text.count(END)!=1: raise SystemExit("bad generated markers")
        return text.split(START,1)[0].rstrip()+"\n\n"+b+"\n"+text.split(END,1)[1].lstrip("\n")
    return text.rstrip()+"\n\n"+b+"\n"

def extract(text):
    if START not in text or END not in text: return None
    return START+text.split(START,1)[1].split(END,1)[0]+END

def sync(d):
    PLAN.write_text(plan(d),encoding="utf-8")
    a=AI.read_text(encoding="utf-8")
    lines=a.splitlines(); hits=[n for n,l in enumerate(lines) if l.startswith("- Current single task:")]
    if len(hits)!=1: raise SystemExit("current task line missing/duplicated")
    lines[hits[0]]=task(d); a="\n".join(lines)+("\n" if a.endswith("\n") else "")
    if START in a: a=replace_block(a,state(d))
    else:
        lines=a.splitlines(); idx=next(n for n,l in enumerate(lines) if l.startswith("- Current single task:"))
        lines[idx+1:idx+1]=["",state(d),""]; a="\n".join(lines).rstrip()+"\n"
    AI.write_text(a,encoding="utf-8")
    PORTFOLIO.write_text(replace_block(PORTFOLIO.read_text(encoding="utf-8"),portfolio(d)),encoding="utf-8")

def check(d):
    if PLAN.read_text(encoding="utf-8")!=plan(d): raise SystemExit("generated architecture plan is stale; run --sync")
    a=AI.read_text(encoding="utf-8")
    if task(d) not in a or extract(a)!=state(d): raise SystemExit("AI project state is stale; run --sync")
    if extract(PORTFOLIO.read_text(encoding="utf-8"))!=portfolio(d): raise SystemExit("portfolio plan is stale; run --sync")
    c=CAPACITY.read_text(encoding="utf-8")
    for marker in ["status: DEFERRED_NOT_REQUIRED_FOR_PORTFOLIO_CLOSURE","live_baseline: DEFERRED_NOT_REQUIRED_FOR_PORTFOLIO_CLOSURE","next_checkpoint: NONE_PORTFOLIO_CLOSED"]:
        if marker not in c: raise SystemExit("capacity Work Package is not portfolio-deferred: "+marker)
    print("case_c_architecture_ledger=passed"); print("current_phase="+d["current_phase"]); print("open_blocker_count="+str(len(blockers(d))))

def main():
    p=argparse.ArgumentParser(); g=p.add_mutually_exclusive_group(required=True); g.add_argument("--check",action="store_true"); g.add_argument("--sync",action="store_true")
    a=p.parse_args(); d=load()
    if a.sync: sync(d)
    check(d)
if __name__=="__main__": main()
